#' An example FunctionalSingleCellExperiment
#'
#' Contains sample data for a functional single-cell experiment.
#'
#' There are two `SingleCellExperiments`:
#'
#' 1. `rnaseq`: a `SCERnaSeq` object containing a single-cell mRNA sequencing
#'    (10x Genomics V2 3´ ) cell/gene counts matrix in the `counts` slot.
#'    Log-normalized counts are in the `logcounts` slot.
#'
#' 2. `haircut`: a `SCEHaircut` object containing a Haircut experiment using DNA
#'    repair oligos. Counts are in the `counts` slot, and centered log-ratio
#'    normalized counts are in the `logcounts` slot.
#'
#' Haircut repair substrates include:
#'
#' * A "normal" DNA oligo (`Normal_`)
#' * a ribonucleotide (rG) at position 45 (`Ribo_`)
#' * an Abasic site at position 45 (`Abasic_`)
#' * a uracil:adenosine base-pair, with uracil at position 45 (`Uracil_`)
#' * a uracil:guanosine base-pair, with uracil at position 45 (`GU_`)
#'
#' @source Generated by `data-raw/fsce_small.R`.
"fsce_small"
