#' Calculate and plot coverage across hairpins
#'
#' @param hcut_obj haircut_object generated by create_haircut
#' @param cells_to_plot vector of cells ids to include in coverage calculation
#' @param return_df return coverage values as data.frame (default = FALSE)
#' @param ... additional arguments to pass to [`plot_hairpin_coverage`]
#'
#' @importFrom purrr map_dfr
#' @export
plot_hairpin <- function(hcut_obj,
                         cells_to_plot = NULL,
                         return_df = FALSE,
                         ...) {

  if (is.null(cells_to_plot)){
    cells_to_plot <- colnames(counts(hcut_obj[["hcut"]]))
  }

  hcut_metadata <- colData(hcut_obj[["hcut"]])[cells_to_plot, , drop = FALSE]
  counts <- counts(hcut_obj[["hcut"]])

  per_sample_cell_ids <- split(rownames(hcut_metadata), hcut_metadata$sample_id)

  ## compute per sample per adduct position counts
  plt_dat <- purrr::map_dfr(per_sample_cell_ids,
                            function(cell_ids) {
                              hairpin_info <- as.data.frame(rowData(hcut_obj[["hcut"]]))
                              hairpin_info$count <- rowSums(counts[, cell_ids, drop = FALSE])
                              hairpin_info
                            },
                            .id = "sample")

  ## fix types
  plt_dat$sample <- as.character(plt_dat$sample)
  plt_dat$position <- as.numeric(plt_dat$position)

  if (return_df) {
    return(plt_dat)
  }

  plot_hairpin_coverage(plt_dat, "position", "count", ...)

}

#' Plot coverage across hairpins
#'
#' @param df haircut_object generated by create_haircut
#' @param x column to use for x-axis
#' @param y column to use for y-axis
#' @param col column to use for coloring lines (defaults to "Sample")
#' @param x_lab label for x axis (defaults to "Position")
#' @param y_lab label for y axis (defaults to "Counts")
#' @param pal RcolorBrewer palette to use for coloring col (defaults to "Set1")
#' @param point show points in addition to lines (defaults to FALSE)
#' @param facet_by_hairpin plot each hairpin individually (defaults to TRUE)
#' @param pt_alpha passed to pt.alpha argument for [`ggplot2::geom_line()`] (defaults to 0.7)
#' @param pt_size passed to pt.size argument for [`ggplot2::geom_line()`] (defaults to 0.8)
#' @param xlimits two element numeric vector to supply to [`ggplot::xlim()`] (defaults to NULL)
#'
#' @import ggplot2
#' @importFrom purrr map_dfr
#' @export
plot_hairpin_coverage <- function(df,
                                  x,
                                  y,
                                  col = "sample",
                                  x_lab = "Position",
                                  y_lab = "Counts",
                                  pal = "Set1",
                                  point = F,
                                  facet_by_hairpin = TRUE,
                                  pt_alpha = 0.7,
                                  pt_size = 0.8,
                                  xlimits = NULL) {


  p <- ggplot(df, aes_string(x = x, y = y)) +
    geom_line(aes_string(color = col), alpha = pt_alpha, size = pt_size) +
    cowplot::theme_cowplot() +
    scale_color_brewer(palette = pal) +
    ylab(y_lab) +
    xlab(x_lab)

  if (all(c("adduct_position1", "adduct_position2") %in% colnames(df))){
    p <- p +
      geom_vline(
        xintercept = df$adduct_position1[1],
        linetype = "dotted",
        color = "black",
        size = 1
      ) +
      geom_vline(
        xintercept = df$adduct_position2[1],
        linetype = "dotted",
        color = 'black',
        size = 1
      )
  }

  if (!is.null(xlimits)){
    p + xlim(xlimits)
  }

  if (point) {
    p <- p + geom_point(aes_string(color = col))
  }

  if (facet_by_hairpin) {
    p <- p + facet_wrap( ~ hairpin)
  }
  p
}
