#' Load mtx formatted 10x or haircut matrices
#'
#' @param path path to directory with mtx matrix
#' @param cell_prefix string to prefix to cell_id  (default = NULL)
#' @param strip_10x_suffix remove numeric suffix added by 10x e.g. change
#'   "TTTGTCAAGGTGTGGT-1" to "TTTGTCAAGGTGTGGT" (default = TRUE)
#' @param use_gene_symbols If TRUE use gene symbols as row.names, if false then
#'   gene_ids will be used (default = TRUE)
#' @param matrix_fn filename for matrix
#' @param features_fn filename for genes file
#' @param barcodes_fn filename for barcodes file
#'
#' @export
read_matrix <- function(path,
                        cell_prefix = NULL,
                        strip_10x_suffix = TRUE,
                        use_gene_symbols = TRUE,
                        matrix_fn = "matrix.mtx.gz",
                        features_fn = "features.tsv.gz",
                        barcodes_fn = "barcodes.tsv.gz") {

  filenames <- list(matrix = matrix_fn,
                    features = features_fn,
                    barcodes = barcodes_fn)

  fns <- dir(path, full.names = TRUE)

  filenames <- map(filenames, ~fs::path_join(c(path, .x)))

  if (!all(filenames %in% fns)) {
    # check for gzipped equivalents
    gzipped_fns <- paste0(filenames, ".gz")
    is_gzipped <- gzipped_fns %in% fns

    # rename if found
    if(any(is_gzipped)) {
      filenames[is_gzipped] <- gzipped_fns[is_gzipped]
    } else {
      stop(paste0("missing required files: ",
                  unlist(filenames[!filenames %in% fns]),
                  "\n"))
    }
  }

  # assign column names based on feature file type
  n_fcols <- count_cols(filenames$features)
  if (n_fcols == 3) {
    col_args = fcols_10x_v3
  } else if (n_fcols == 2) {
    col_args = fcols_10x_v2
  } else if (n_fcols == 1) {
    col_args = fcols_haircut
  } else {
    stop("unknown feature file format", call. = FALSE)
  }

  features <- suppressMessages(do.call(readr::read_tsv,
                                       c(file = filenames$features,
                                         col_args)))

  bcs <- readLines(filenames$barcodes)

  mat <- Matrix::readMM(filenames$matrix)

  if (strip_10x_suffix) {
    bcs <- stringr::str_remove(bcs, "-[0-9]+$")
  }

  if (!is.null(cell_prefix)) {
    bcs <- stringr::str_c(cell_prefix, "_", bcs)
  }

  if (use_gene_symbols & ("gene_symbol" %in% colnames(features))) {
    features_ids <- features[["gene_symbol"]]
  } else {
    # default to first column
    features_ids <- features[[1]]
  }

  features_ids <- make.unique(features_ids)
  rownames(mat) <- features_ids
  colnames(mat) <- bcs

  mat
}

#' Return number of cols from first line of a file
#' @noRd
count_cols <- function(file,
                       tokenizer_fun = tokenizer_tsv()){
  readr::count_fields(file,
                      tokenizer = tokenizer_fun, n_max = 1)
}


# Column definitions for features.tsv files -----------------------------

#' @noRd
fcols_10x_v3 <- list(col_types = 'ccc',
                     col_names = c("gene_id", "gene_symbol", "type"))
#' @noRd
fcols_10x_v2 <- list(col_types = "cc",
                     col_names = c("gene_id", "gene_symbol"))
#' @noRd
fcols_haircut <- list(col_types = "c",
                      col_names = "feature")

#' Convert umitools flat format tsv to sparseMatrix .mtx format
#'
#' @param count_file path to umitools output file
#' @param output_path path for output files. matrix.mtx.gz, barcodes.tsv.gz and features.tsv.gz
#' will be generated at the supplied path, or by default created in same directory as
#' the `count_file`.
#' @param ... additional arguments to pass to [`readr::read_tsv()`]
#'
#' @importFrom R.utils gzip
#' @importFrom readr read_tsv
#' @importFrom Matrix readMM
#' @importFrom fs path_dir
#'
#' @export
umitools_to_mtx <- function(count_file,
                            output_path = NULL,
                            ...) {

  dat <- readr::read_tsv(count_file, ...)

  barcodes <- unique(dat$cell)
  genes <- unique(dat$gene)

  dat$gene_idx <- match(dat$gene, genes)
  dat$cell_idx <- match(dat$cell, barcodes)

  mat <- Matrix::sparseMatrix(i = dat$gene_idx,
                              j = dat$cell_idx,
                              x = dat$count)

  if(is.null(output_path)) {
    output_path <- fs::path_dir(count_file)
  }

  if(!dir.exists(output_path)) {
    dir.create(output_path, recursive = TRUE)
  }

  Matrix::writeMM(mat, file.path(output_path, "matrix.mtx"))
  R.utils::gzip(file.path(output_path, "matrix.mtx"),
                overwrite = TRUE, remove = TRUE)

  readr::write_lines(genes, file.path(output_path, "features.tsv.gz"))
  readr::write_lines(barcodes, file.path(output_path, "barcodes.tsv.gz"))
}

#' Provide path to scrunchy internal data
#'
#' @param x file name
#'
#' @export
scrunchy_data <- function(x) {
  system.file("extdata", x, package = "scrunchy", mustWork = TRUE)
}

#' Load count matrix in CSV format
#'
#' Generated by scrunchy pipeline
#'
#' @param csv path to CSV file
#'
#' @return `data.frame` with cells as row.names
#'
#' @export
load_matrix_csv <- function(csv) {
  suppressWarnings(
    x <- readr::read_csv(
      csv,
      col_names = TRUE,
      cols(
        id = col_character(),
        .default = col_double()
      )
    )
  )

  x <- as.data.frame(x)
  names(x)[[1]] <- "rowname"

  rownames(x) <- x[["rowname"]]
  x[["rowname"]] <- NULL

  x
}
