#' Load 10x mtx matrix as sparseMatrix
#'
#' @param path path to 10x directory with mtx matrix
#' @param cell_prefix string to prefix to cell_id  (default = NULL)
#' @param strip_10x_suffix remove numeric suffix added by 10x e.g. change
#'   "TTTGTCAAGGTGTGGT-1" to "TTTGTCAAGGTGTGGT" (default = TRUE)
#' @param use_gene_symbols If TRUE use gene symbols as row.names, if false then
#'   gene_ids will be used (default = TRUE)
#'
#' @export
read_10x_matrix <- function(path,
                            cell_prefix = NULL,
                            strip_10x_suffix = TRUE,
                            use_gene_symbols = TRUE) {
  fns <- dir(path)
  fns_needed <- c("barcodes.tsv", "genes.tsv", "matrix.mtx")

  if (!all(fns_needed %in% fns)) {
    stop(paste0("missing required 10x file: ", fns_needed[!fns_needed %in% fns], "\n"))
  }

  bcs <- readLines(file.path(path, "barcodes.tsv"))
  genes <- suppressMessages(readr::read_tsv(
    file.path(path, "genes.tsv"),
    col_names = c("gene_id", "gene_symbol")
  ))

  mat <- Matrix::readMM(file.path(path, "matrix.mtx"))

  if (strip_10x_suffix) {
    bcs <- stringr::str_remove(bcs, "-[0-9]+$")
  }

  if (!is.null(cell_prefix)) {
    bcs <- stringr::str_c(cell_prefix, "_", bcs)
  }

  if (use_gene_symbols) {
    genes_out <- genes[["gene_symbol"]]
  } else {
    genes_out <- genes[["gene_id"]]
  }

  genes_out <- make.unique(genes_out)
  rownames(mat) <- genes_out
  colnames(mat) <- bcs

  mat
}

#' Convert umitools flat format tsv to sparseMatrix .mtx format
#'
#' @param count_file path to umitools output file
#' @param output_path path for output files. matrix.mtx, barcodes.tsv and genes.tsv
#' will be generated in supplied path, or by default creates in same directory as
#' the count_file.
#' @param ... additional arguments to pass to [`readr::read_tsv()`]
#'
#' @importFrom R.utils gzip
#' @importFrom readr read_tsv
#' @importFrom Matrix readMM
#' @importFrom fs path_dir
#'
#' @export
umitools_to_mtx <- function(count_file,
                            output_path = NULL,
                            ...) {

  dat <- readr::read_tsv(count_file, ...)

  barcodes <- unique(dat$cell)
  genes <- unique(dat$gene)

  dat$gene_idx <- match(dat$gene, genes)
  dat$cell_idx <- match(dat$cell, barcodes)

  mat <- Matrix::sparseMatrix(i = dat$gene_idx,
                              j = dat$cell_idx,
                              x = dat$count)

  if(is.null(output_path)) {
    output_path <- fs::path_dir(count_file)
  }

  if(!dir.exists(output_path)) {
    dir.create(output_path, recursive = TRUE)
  }

  Matrix::writeMM(mat, file.path(output_path, "matrix.mtx"))
  R.utils::gzip("matrix.mtx", overwrite = TRUE, remove = TRUE)

  writeLines(genes, file.path(output_path, "genes.tsv"))
  writeLines(barcodes, file.path(output_path, "barcodes.tsv"))
}

#' Provide path to scrunchy internal data
#'
#' @param x file name
#'
#' @export
scrunchy_data <- function(x) {
  system.file("extdata", x, package = "scrunchy", mustWork = TRUE)
}

#' Load count matrix in CSV format
#'
#' Generated by scrunchy pipeline
#'
#' @param csv path to CSV file
#'
#' @return `data.frame` with cells as row.names
#'
#' @export
load_matrix_csv <- function(csv) {
  suppressWarnings(
    x <- readr::read_csv(
      csv,
      col_names = TRUE,
      cols(
        id = col_character(),
        .default = col_double()
      )
    )
  )

  x <- as.data.frame(x)
  names(x)[[1]] <- "rowname"

  rownames(x) <- x[["rowname"]]
  x[["rowname"]] <- NULL

  x
}
